"""Add document_versions and update documents

Revision ID: 2ea81d2f2ec2
Revises: 103154751807
Create Date: 2026-08-13 14:20:57.523299

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ea81d2f2ec2"
down_revision: str | Sequence[str] | None = "103154751807"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("uploaded_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("documents", sa.Column("title", sa.String(length=255), nullable=False))
    op.add_column("documents", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.drop_column("documents", "filename")
    op.drop_column("documents", "s3_key")
    op.drop_column("documents", "uploaded_at")
    op.drop_column("documents", "file_size")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "documents",
        sa.Column(
            "uploaded_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "documents",
        sa.Column("s3_key", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column("filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("documents", "created_at")
    op.drop_column("documents", "title")
    op.drop_table("document_versions")
    # ### end Alembic commands ###
