"""add project_members table for rbac

Revision ID: 7250ca4ed463
Revises: 1d715fc41aac
Create Date: 2026-08-21 14:39:25.588247

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '7250ca4ed463'
down_revision: Union[str, Sequence[str], None] = '1d715fc41aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
